### ISSUE TITLE
Publish on Github pages

### ISSUE THREAD

**Issue by mk-pmb** [daverix/HTML5-Pong#1]
Hi! I'd love to try your game, but the demo URL website doesn't serve me, maybe because I'm behind TOR. Could you enable Github pages in the repo options and set it to master branch? That way it would hopefully show up on https://daverix.github.io/HTML5-Pong/ .

**Comment by daverix** [comment]
The game is available at https://daverix.net/projects/pong/ or http://pong.daverix.net

**Comment by mk-pmb** [comment]
I guess you're not interested in serving people behind TOR then. Fortunately it's not a big deal here.

**Comment by daverix** [comment]
Just download the source and run it locally then?

**Comment by daverix** [comment]
Ok now it's enabled.

**Comment by mk-pmb** [comment]
Nice, thanks!
